name: digi_diagnos
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  pinput: ^3.0.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  country_picker: ^2.0.18
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  image_picker: ^1.0.4
  font_awesome_flutter: ^10.2.1
  table_calendar: ^3.0.8
  lottie: ^2.0.0
  dio: ^4.0.6
  rating_dialog: ^2.0.4
  flutter_rating_bar: ^4.0.0
  upi_india: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700